model:
  class_path: BiEncoderModule
  init_args:
    model_name_or_path: ./tests/data/test_model
    config:
      class_path: ColConfig
      init_args:
        similarity_function: dot
        query_aggregation_function:  sum
        query_expansion: true
        query_length: 32
        doc_length: 256
        normalize: true
        add_marker_tokens: true
        embedding_dim: 128
        linear_bias: false
    loss_functions:
      - class_path: RankNet
        