trainer:
  callbacks+:
  - class_path: ConstantSchedulerWithWarmup
    init_args:
      keys:
      - loss_functions.1.query_weight
      - loss_functions.1.doc_weight
      num_warmup_steps: 20_000
      num_delay_steps: 50_000
  