model:
  class_path: ColBERTModule
  init_args:
    model_name_or_path: null
    config:
      class_path: ColBERTConfig
      init_args:
        similarity_function: cosine
        aggregation_function:  sum
        query_expansion: true
        query_length: 32
        attend_to_query_expanded_tokens: false
        doc_expansion: false
        doc_length: 512
        attend_to_doc_expanded_tokens: false
        normalize: true
        add_marker_tokens: true
        embedding_dim: 128
        linear_bias: false
    loss_function:
      class_path: LocalizedContrastive
      init_args:
        reduction: mean