trainer:
  accelerator: auto
  strategy: auto
  devices: auto
  num_nodes: 1
  precision: null
  logger:
    class_path: CustomWandbLogger
    init_args:
      project: tide
  callbacks:
    class_path: ModelCheckpoint
    init_args:
      every_n_train_steps: 50000
      save_on_train_epoch_end: true
  max_epochs: null
  max_steps: -1
  val_check_interval: 10000
  check_val_every_n_epoch: null
  num_sanity_val_steps: 2
  log_every_n_steps: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  inference_mode: true
  use_distributed_sampler: true
