name: Tests
on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
    types:
      - ready_for_review
  workflow_dispatch: {}

jobs:
  run-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install self
        working-directory: ${{github.workspace}}
        run: |
          # Since splade makes problems otherwise:
          pip3 install "splade@git+https://github.com/naver/splade.git" --break-system-packages --no-deps
          pip3 install omegaconf==2.1.2 --break-system-packages
          pip3 install .[test,dev] --break-system-packages
      - name: Run tests
        working-directory: ${{github.workspace}}
        run: pytest tests
